In [1]:
# 1. Create a 1D NumPy Array:/
import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [2]:
# 2. Inspection and Properties:
# Shape
print("Shape:", temperatures_w1.shape)

# Data type
print("Data Type:", temperatures_w1.dtype)

# Number of elements
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


In [4]:
# 3. Array Operations:
fahrenheit = (temperatures_w1 * 9/5) + 32

print("Temperature in Fahrenheit:")
print(fahrenheit)

print("Maximum Temperature:", temperatures_w1.max())
print("Minimum Temperature:", temperatures_w1.min())
print("Mean Temperature:", temperatures_w1.mean())

Temperature in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [5]:
# 4. Array Slicing and Indexing:

first_three_days = temperatures_w1[:3]

print("First Three Days:")
print(first_three_days)
weekend = temperatures_w1[-2:]

print("Weekend Temperatures:")
print(weekend)
middle_three_days = temperatures_w1[2:5]

print("Middle Three Days:")
print(middle_three_days)

First Three Days:
[22.5 25.3 20.8]
Weekend Temperatures:
[24.8 21.9]
Middle Three Days:
[20.8 23.4 26.1]


In [6]:
# 5. Create a 2D Array:

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("Temperature Data:")
print(temperatures)

Temperature Data:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [7]:
# 6. Inspect and Slice the 2D Array:

print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)
week1 = temperatures[0]

print("Week 1:")
print(week1)
week2 = temperatures[1]

print("Week 2:")
print(week2)
week2_weekend = temperatures[1, -2:]

print("Week 2 Weekend:")
print(week2_weekend)
weekends = temperatures[:, -2:]

print("Weekends for Both Weeks:")
print(weekends)

Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14
Week 1:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 2 Weekend:
[22.8 20.1]
Weekends for Both Weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [8]:
# 1. Creating Pandas Series:
import pandas as pd
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [13]:
# 2. Indexing and Slicing:

print("1st Rank Mark:", marks.iloc[0])

top_three = marks.iloc[:3]

print("Top 3 Ranks:")
print(top_three)

above_90 = marks[marks > 90]

print("Marks Greater Than 90:")
print(above_90)

1st Rank Mark: 95
Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64


In [14]:
# 3. Manipulating Series:

marks.loc['Rank1'] = 100

print(marks)

marks = marks.drop('Rank5')

print("After Removing Rank5:")
print(marks)
cgpa = marks / 10

print("CGPA:")
print(cgpa)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
After Removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [15]:
# Pandas DataFrame:
# 1. Creating Pandas DataFrame:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [17]:
# 2. Data Exploration:

print(transactions)
print(transactions.head())
print(transactions.head())
print("Shape:", transactions.shape)
print("Column Names:")
print(transactions.columns)
print("Column Names:")
print(transactions.columns)
print("Data Types:")
print(transactions.dtypes)
print(transactions[['ProductCategory', 'Amount']])
print(transactions.iloc[:, -3:])
filtered_data = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered_data)
print(transactions['ProductCategory'].value_counts())
print(transactions['Region'].unique())
region_mean = transactions.groupby('Region')['Amount'].mean()

print(region_mean)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North 

In [19]:
# 3. Manipulating the DataFrame:
# Modify the 'Amount' for the transaction with TransactionID 102 to 165.
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print(transactions)
# Add a new column 'Discount' by calculating 10% of the 'Amount'.
transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)
# Remove the row with TransactionID 109.
transactions = transactions[
    transactions['TransactionID'] != 109
]

print(transactions)
# Delete the 'Discount' column from the DataFrame.
transactions = transactions.drop(columns=['Discount'])

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7       